# Generated by Django 2.2.10 on 2020-06-01 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200601_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='todo_count',
            new_name='todos_count',
        ),
    ]
